### ISSUE TITLE
Pop up Message Boxes

### ISSUE THREAD

**Issue by ghost** [pgr-hub-malware-studio/cxk-trojan#3]
Pop up message boxes after drawing random icons
Title is "蔡徐坤"
And the contents will be updated to the source file soon

Presented by NyanMEMZ

**Comment by Dobby233Liu** [comment]
I prefer the MesssageBox content to be random

**Comment by ghost** [comment]
> I prefer the MesssageBox content to be random

Sure. The content will be selected from the message array randomly.

**Comment by ghost** [comment]
This feature has been implemented
